import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";

/**
 * POST /api/coach
 *
 * Accepts a PoseSummary JSON + conversation history and returns
 * a short coaching message generated by OpenAI.
 *
 * Request body:
 * {
 *   summary: PoseSummary,          // current pose snapshot
 *   history: { role, content }[]   // recent coach conversation (last ~6 turns)
 * }
 *
 * Response:
 * { message: string }
 */

const SYSTEM_PROMPT = `You are an energetic, concise dance coach giving real-time feedback to someone learning a move from a YouTube video.

You receive a JSON snapshot of their current pose and movement quality. Use it to give ONE short coaching line (max 12 words).

Guidelines:
- Be encouraging but specific.
- If score >= 80 and trend is improving/steady, give hype ("Yes! That energy!" / "Clean lines — keep it!").
- If score < 60, address the top issue with an actionable cue ("Lift those arms above your shoulders!" / "Wider stance — bend your knees!").
- If motionEnergy < 0.01, they're standing still — prompt them to move.
- If motionEnergy > 0.1, they're flailing — tell them to control it.
- If armSymmetry > 0.15, cue them to mirror their arms.
- If armHeight > 0.1, their hands are low — cue them to raise hands.
- If torsoLean magnitude > 0.05, cue them to center their weight.
- Reference the trend: if declining, say "let's get it back"; if improving, acknowledge progress.
- Never repeat the same exact line twice in a row.
- Speak like a real coach: short, punchy, motivating.
- Reply with ONLY the coaching line, nothing else. No quotes, no JSON.`;

export async function POST(req: NextRequest) {
  try {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      // Fallback: return a rule-based message if no API key configured
      return NextResponse.json(
        { message: "Set OPENAI_API_KEY in .env.local to enable AI coach!" },
        { status: 200 }
      );
    }

    const { summary, history } = await req.json();

    if (!summary) {
      return NextResponse.json(
        { error: "Missing summary in request body" },
        { status: 400 }
      );
    }

    const openai = new OpenAI({ apiKey });

    // Build messages array
    const messages: OpenAI.Chat.ChatCompletionMessageParam[] = [
      { role: "system", content: SYSTEM_PROMPT },
    ];

    // Include recent conversation history (last 6 exchanges for context)
    if (Array.isArray(history)) {
      for (const msg of history.slice(-6)) {
        messages.push({
          role: msg.role as "user" | "assistant",
          content: msg.content,
        });
      }
    }

    // Current pose data as the new user message
    messages.push({
      role: "user",
      content: `Current pose snapshot:\n${JSON.stringify(summary, null, 2)}`,
    });

    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages,
      max_tokens: 40,
      temperature: 0.9,
    });

    const message =
      completion.choices[0]?.message?.content?.trim() ?? "Keep moving!";

    // Generate speech audio via OpenAI TTS
    let audio: string | undefined;
    try {
      const ttsRes = await openai.audio.speech.create({
        model: "tts-1",
        voice: "nova",
        input: message,
        response_format: "mp3",
        speed: 1.1,
      });
      const buf = Buffer.from(await ttsRes.arrayBuffer());
      audio = buf.toString("base64");
    } catch (ttsErr) {
      console.error("TTS error (falling back to text only):", ttsErr);
    }

    return NextResponse.json({ message, audio });
  } catch (err) {
    console.error("Coach API error:", err);
    return NextResponse.json(
      { message: "Keep going! You've got this!" },
      { status: 200 }
    );
  }
}
